/*
	Master
	Authors: ChimpanG
*/

-----------------------------------------------
-- ModCheck
-----------------------------------------------

INSERT INTO ModCheck (ModType) VALUES ('CITY_STATES_EXPANDED');

-----------------------------------------------
-- CSE_Master
-----------------------------------------------

INSERT INTO CSE_Master
		(CityState,			New,	ProposedType,		FallbackCity,		Ethnicity,				Requires,	Removed	)
VALUES	('AKKAD',			0,		'MILITARISTIC',		NULL,				'ETHNICITY_MEDIT',		'XP2',		NULL	),
		('AMSTERDAM',		0,		'TRADE',			'GRONIGEN',			'ETHNICITY_EURO',		'BASE',		'XP1'	),
		('ANTANANARIVO',	0,		'CULTURAL',			'TBD',				'ETHNICITY_MUGHAL',		'VIKINGS',	NULL	),
		('ANTIOCH',			0,		'TRADE',			'SELEUCIA_PIERIA',	'ETHNICITY_MEDIT',		'XP1',		NULL	),
		('ARMAGH',			0,		'RELIGIOUS',		'TBD',				'ETHNICITY_EURO',		'VIKINGS',	NULL	),
		('AUCKLAND',		0,		'TRADE',			'GRONIGEN',			'ETHNICITY_EURO',		'VIKINGS',	NULL	),
		('BABYLON',			0,		'SCIENTIFIC',		'TBD',				'ETHNICITY_EURO',		'XP1',		NULL	),
		('BOLOGNA',			0,		'SCIENTIFIC',		'TBD',				'ETHNICITY_EURO',		'XP2',		NULL	),
		('BUENOS_AIRES',	0,		'INDUSTRIAL',		'SANTIAGO',			'ETHNICITY_SOUTHAM',	'BASE',		NULL	),
		('BRUSSELS',		0,		'INDUSTRIAL',		'ANTWERP',			'ETHNICITY_EURO',		'BASE',		NULL	),
		('CAHOKIA',			0,		'COMMERCIAL',		'TBD',				'ETHNICITY_SOUTHAM',	'XP2',		NULL	),
		('CARDIFF',			0,		'INDUSTRIAL',		'CAERPHILLY',		'ETHNICITY_EURO',		'XP2',		NULL	),
		('CARTHAGE',		0,		'MILITARISTIC',		'TUNIS',			'ETHNICITY_AFRICAN',	'BASE',		'XP2'	),
		('FEZ',				0,		'SCIENTIFIC',		TBD,				'ETHNICITY_AFRICAN',	'XP2',		NULL	),
		('GENEVA',			0,		'SCIENTIFIC',		'BERN',				'ETHNICITY_EURO',		'BASE',		NULL	),
		('GRANADA',			0,		'MILITARISTIC',		'TBD',				'ETHNICITY_EURO',		'VIKINGS',	NULL	),
		('HATTUSA',			0,		'SCIENTIFIC',		'TBD',				'ETHNICITY_MEDIT',		'BASE',		NULL	),
		('HONG_KONG',		0,		'PRODUCTION',		'TBD',				'ETHNICITY_ASIAN',		'BASE',		NULL	),
		('JAKARTA',			0,		'TRADE',			'BANDAR_BRUNEI',	'ETHNICITY_ASIAN',		'BASE',		NULL	),
		('JERUSALEM',		0,		'RELIGIOUS',		'TBD',				'ETHNICITY_MEDIT',		'BASE',		NULL	),
		('KABUL',			0,		'MILITARISTIC',		'TBD',				'ETHNICITY_MEDIT',		'BASE',		NULL	),
		('KANDY',			0,		'RELIGIOUS',		'TBD',				'ETHNICITY_AFRICAN',	'BASE',		NULL	),
		('KUMASI',			0,		'CULTURAL',			'TBD',				'ETHNICITY_AFRICAN',	'BASE',		NULL	),
		('LA_VENTA',		0,		'RELIGIOUS',		'TBD',				'ETHNICITY_SOUTHAM',	'BASE',		NULL	),
		('LISBON',			0,		'TRADE',			'TBD',				'ETHNICITY_EURO',		'BASE',		NULL	),
		('MEXICO_CITY',		0,		'INDUSTRIAL',		'TBD',				'ETHNICITY_SOUTHAM',	'XP2',		NULL	),
		('MOHENJO_DARO',	0,		'CULTURAL',			'TBD',				'ETHNICITY_AFRICAN',	'BASE',		NULL	),
		('MUSCAT',			0,		'TRADE',			'MARRAKECH',		'ETHNICITY_AFRICAN',	'VIKINGS',	NULL	),
		('NAN_MADOL',		0,		'CULTURAL',			'TBD',				'ETHNICITY_ASIAN',		'BASE',		NULL	),
		('NAZCA',			0,		'RELIGIOUS',		'TBD',				'ETHNICITY_SOUTHAM',	'XP2',		NULL	),
		('NGAZARGAMU',		0,		'MILITARISTIC',		'TBD',				'ETHNICITY_AFRICAN',	'XP2',		NULL	),
		('PALENQUE',		0,		'MILITARISTIC',		'TBD',				'ETHNICITY_SOUTHAM',	'VIKINGS',	NULL	),
		('PRESLAV',			0,		'MILITARISTIC',		'TBD',				'ETHNICITY_EURO',		'BASE',		NULL	),
		('RAPA_NUI',		0,		'CULTURAL',			'TBD',				'ETHNICITY_SOUTHAM',	'XP2',		NULL	),
		('SEOUL',			0,		'SCIENTIFIC',		'TBD',				'ETHNICITY_EURO',		'BASE',		'XP1'	),
		('STOCKHOLM',		0,		'SCIENTIFIC',		'TBD',				'ETHNICITY_EURO',		'BASE',		'XP2'	),
		('TORONTO',			0,		'INDUSTRIAL',		'MONTREAL',			'ETHNICITY_EURO',		'BASE',		'XP2'	),
		('VALLETTA',		0,		'MILITARISTIC',		'TBD',				'ETHNICITY_MEDIT',		'BASE',		NULL	),
		('VILNIUS',			0,		'CULTURAL',			'TBD',				'ETHNICITY_EURO',		'BASE',		NULL	),
		('YEREVAN',			0,		'MILITARISTIC',		'TBD',				'ETHNICITY_MEDIT',		'BASE',		NULL	),
		('ZANZIBAR',		0,		'TRADE',			'TBD',				'ETHNICITY_AFRICAN',	'BASE',		NULL	);

-----------------------------------------------
-- CSE_StartBias
-----------------------------------------------

INSERT INTO CSE_StartBias
		(CityStateType,		Type,		Object,				Tier	)
VALUES	('AKKAD',			'FEATURE',	'FLOODPLAINS',		2		),
		('AKKAD',			'TERRAIN',	'DESERT',			5		),
		('AKKAD',			'TERRAIN',	'DESERT_HILLS',		5		),
		('AMSTERDAM',		'FEATURE',	'MARSH',			5		),
		('AMSTERDAM',		'TERRAIN',	'COAST',			3		),
		('ANTANANARIVO',	'TERRAIN',	'COAST',			5		),
		('ANTIOCH',			'TERRAIN',	'COAST',			5		),
		('ANTIOCH',			'FEATURE',	'FLOODPLAINS',		3		),
		('ARMAGH',			'TERRAIN',	'GRASS',			5		),
		('ARMAGH',			'TERRAIN',	'GRASS_HILLS',		5		),
		('AUCKLAND',		'TERRAIN',	'COAST',			2		),
		('AUCKLAND',		'TERRAIN',	'GRASS_HILLS',		5		),
		('BABYLON',			'FEATURE',	'FLOODPLAINS',		2		),
		('BABYLON',			'TERRAIN',	'DESERT',			5		),
		('BABYLON',			'TERRAIN',	'DESERT_HILLS',		5		),
		('BOLOGNA',			'TERRAIN',	'GRASS',			5		),
		('BOLOGNA',			'TERRAIN',	'GRASS_HILLS',		5		),
		('BOLOGNA',			'TERRAIN',	'PLAINS',			5		),
		('BOLOGNA',			'TERRAIN',	'PLAINS_HILLS',		5		),
		('BUENOS_AIRES',	'TERRAIN',	'GRASS',			5		),
		('BUENOS_AIRES',	'TERRAIN',	'GRASS_HILLS',		5		),
		('BRUSSELS',		'FEATURE',	'MARSH',			5		),
		('BRUSSELS',		'TERRAIN',	'GRASS',			5		),
		('BRUSSELS',		'TERRAIN',	'GRASS_HILLS',		5		),
		('CAHOKIA',			'TERRAIN',	'PLAINS',			5		),
		('CAHOKIA',			'TERRAIN',	'PLAINS_HILLS',		5		),
		('CARDIFF',			'TERRAIN',	'COAST',			5		),
		('CARDIFF',			'TERRAIN',	'GRASS_HILLS',		5		),
		('CARTHAGE',		'TERRAIN',	'COAST',			5		),
		('CARTHAGE',		'TERRAIN',	'DESERT',			5		),
		('CARTHAGE',		'TERRAIN',	'DESERT_HILLS',		5		),
		('FEZ',				'FEATURE',	'OASIS',			3		),
		('FEZ',				'TERRAIN',	'DESERT',			5		),
		('FEZ',				'TERRAIN',	'DESERT_HILLS',		5		),
		('GENEVA',			'TERRAIN',	'GRASS_MOUNTAIN',	5		),
		('GRANADA',			'TERRAIN',	'PLAINS',			5		),
		('GRANADA',			'TERRAIN',	'PLAINS_HILLS',		5		),
		('HATTUSA',			'TERRAIN',	'PLAINS_HILLS',		5		),
		('HATTUSA',			'TERRAIN',	'DESERT_HILLS',		5		),
		('HONG_KONG',		'TERRAIN',	'COAST',			5		),
		('HONG_KONG',		'TERRAIN',	'GRASS',			5		),
		('HONG_KONG',		'TERRAIN',	'GRASS_HILLS',		5		),
		('JAKARTA',			'TERRAIN',	'COAST',			2		),
		('JAKARTA',			'FEATURE',	'JUNGLE',			2		),
		('JERUSALEM',		'FEATURE',	'FLOODPLAINS',		2		),
		('JERUSALEM',		'TERRAIN',	'DESERT',			5		),
		('JERUSALEM',		'TERRAIN',	'DESERT_HILLS',		5		),
		('KABUL',			'FEATURE',	'FLOODPLAINS',		2		),
		('KABUL',			'TERRAIN',	'DESERT',			5		),
		('KABUL',			'TERRAIN',	'DESERT_HILLS',		5		),
		('KANDY',			'TERRAIN',	'COAST',			5		),
		('KANDY',			'FEATURE',	'JUNGLE',			5		),
		('KUMASI',			'RIVER',	NULL,				5		),
		('LA_VENTA',		'FEATURE',	'JUNGLE',			2		),
		('LISBON',			'TERRAIN',	'COAST',			2		),
		('LISBON',			'TERRAIN',	'PLAINS',			5		),
		('LISBON',			'TERRAIN',	'PLAINS_HILLS',		5		),
		('MEXICO_CITY',		'TERRAIN',	'PLAINS',			5		),
		('MEXICO_CITY',		'TERRAIN',	'PLAINS_HILLS',		5		),
		('MOHENJO_DARO',	'RIVER',	NULL,				5		),
		('MOHENJO_DARO',	'TERRAIN',	'COAST',			3		),
		('MOHENJO_DARO',	'FEATURE',	'JUNGLE',			5		),
		('MUSCAT',			'FEATURE',	'OASIS',			3		),
		('MUSCAT',			'TERRAIN',	'DESERT',			5		),
		('MUSCAT',			'TERRAIN',	'DESERT_HILLS',		5		),
		('NAN_MADOL',		'TERRAIN',	'COAST',			2		),
		('NAN_MADOL',		'FEATURE',	'JUNGLE',			2		),
		('NAZCA',			'TERRAIN',	'DESERT',			3		),
		('NAZCA',			'TERRAIN',	'DESERT_HILLS',		3		),
		('NGAZARGAMU',		'FEATURE',	'JUNGLE',			3		),
		('PALENQUE',		'FEATURE',	'JUNGLE',			3		),
		('PRESLAV',			'TERRAIN',	'GRASS_HILLS',		5		),
		('RAPA_NUI',		'TERRAIN',	'COAST',			2		),
		('RAPA_NUI',		'FEATURE',	'JUNGLE',			3		),
		('RAPA_NUI',		'FEATURE',	'VOLCANO',			3		),
		('SEOUL',			'FEATURE',	'FOREST',			5		),
		('STOCKHOLM',		'TERRAIN',	'TUNDRA',			5		),
		('STOCKHOLM',		'TERRAIN',	'TUNDRA_HILLS',		5		),
		('VILNIUS',			'TERRAIN',	'GRASS',			5		),
		('VILNIUS',			'TERRAIN',	'GRASS_HILLS',		5		),
		('YEREVAN',			'TERRAIN',	'GRASS_MOUNTAIN',	5		),
		('YEREVAN',			'TERRAIN',	'PLAINS_MOUNTAIN',	5		),
		('ZANZIBAR',		'FEATURE',	'JUNGLE',			3		);