/*
	Localisation
	Authors: thecrazyscotsman, ChimpanG
*/

INSERT OR REPLACE INTO LocalizedText (Language, Tag, Text)
VALUES

-----------------------------------------------
-- Scientific
-----------------------------------------------
	
	("en_US",	"LOC_CSE_SCIENTIFIC_TRAIT_SMALL_INFLUENCE_BONUS",		"+2 [ICON_SCIENCE] Science in your [ICON_CAPITAL] Capital."		),
	("en_US",	"LOC_CSE_SCIENTIFIC_TRAIT_MEDIUM_INFLUENCE_BONUS",		"+2 [ICON_SCIENCE] Science in every Library."	),
	("en_US",	"LOC_CSE_SCIENTIFIC_TRAIT_LARGE_INFLUENCE_BONUS",		"+2 [ICON_SCIENCE] Science in every University."	),
	("en_US",	"LOC_CSE_SCIENTIFIC_TRAIT_DESCRIPTION",					"{LOC_MINOR_CIV_SMALL_INFLUENCE_ENVOYS} {LOC_CSE_SCIENTIFIC_TRAIT_SMALL_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_MEDIUM_INFLUENCE_ENVOYS} {LOC_CSE_SCIENTIFIC_TRAIT_MEDIUM_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_LARGE_INFLUENCE_ENVOYS} {LOC_CSE_SCIENTIFIC_TRAIT_LARGE_INFLUENCE_BONUS}"	),

-----------------------------------------------
-- Cultural
-----------------------------------------------
	
	("en_US",	"LOC_CSE_CULTURAL_TRAIT_SMALL_INFLUENCE_BONUS",			"+2 [ICON_CULTURE] Culture in your [ICON_CAPITAL] Capital."	),
	("en_US",	"LOC_CSE_CULTURAL_TRAIT_MEDIUM_INFLUENCE_BONUS",		"+2 [ICON_CULTURE] Culture in every Amphitheater."	),
	("en_US",	"LOC_CSE_CULTURAL_TRAIT_LARGE_INFLUENCE_BONUS",			"+2 [ICON_CULTURE] Culture in every Art Museum or Artifact Museum."	),
	("en_US",	"LOC_CSE_CULTURAL_TRAIT_DESCRIPTION",					"{LOC_MINOR_CIV_SMALL_INFLUENCE_ENVOYS} {LOC_CSE_CULTURAL_TRAIT_SMALL_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_MEDIUM_INFLUENCE_ENVOYS} {LOC_CSE_CULTURAL_TRAIT_MEDIUM_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_LARGE_INFLUENCE_ENVOYS} {LOC_CSE_CULTURAL_TRAIT_LARGE_INFLUENCE_BONUS}"	),

-----------------------------------------------
-- Trade
-----------------------------------------------
	
	("en_US",	"LOC_CSE_TRADE_TRAIT_SMALL_INFLUENCE_BONUS",			"+2 [ICON_GOLD] Gold in your [ICON_CAPITAL] Capital."			),
	("en_US",	"LOC_CSE_TRADE_TRAIT_MEDIUM_INFLUENCE_BONUS",			"+2 [ICON_GOLD] Gold in every Market."			),
	("en_US",	"LOC_CSE_TRADE_TRAIT_LARGE_INFLUENCE_BONUS",			"+2 [ICON_GOLD] Gold in every Bank."			),
	("en_US",	"LOC_CSE_TRADE_TRAIT_DESCRIPTION",						"{LOC_MINOR_CIV_SMALL_INFLUENCE_ENVOYS} {LOC_CSE_TRADE_TRAIT_SMALL_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_MEDIUM_INFLUENCE_ENVOYS} {LOC_CSE_TRADE_TRAIT_MEDIUM_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_LARGE_INFLUENCE_ENVOYS} {LOC_CSE_TRADE_TRAIT_LARGE_INFLUENCE_BONUS}"	),

-----------------------------------------------
-- Religious
-----------------------------------------------

	("en_US",	"LOC_CSE_RELIGIOUS_TRAIT_SMALL_INFLUENCE_BONUS",		"+2 [ICON_FAITH] Faith in your [ICON_CAPITAL] Capital."			),
	("en_US",	"LOC_CSE_RELIGIOUS_TRAIT_MEDIUM_INFLUENCE_BONUS",		"+2 [ICON_FAITH] Faith in every Shrine."			),
	("en_US",	"LOC_CSE_RELIGIOUS_TRAIT_LARGE_INFLUENCE_BONUS",		"+2 [ICON_FAITH] Faith in every Temple."	),
	("en_US",	"LOC_CSE_RELIGIOUS_TRAIT_DESCRIPTION",					"{LOC_MINOR_CIV_SMALL_INFLUENCE_ENVOYS} {LOC_CSE_RELIGIOUS_TRAIT_SMALL_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_MEDIUM_INFLUENCE_ENVOYS} {LOC_CSE_RELIGIOUS_TRAIT_MEDIUM_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_LARGE_INFLUENCE_ENVOYS} {LOC_CSE_RELIGIOUS_TRAIT_LARGE_INFLUENCE_BONUS}"	),

-----------------------------------------------
-- Militaristic
-----------------------------------------------
	
	("en_US",	"LOC_CSE_MILITARISTIC_TRAIT_SMALL_INFLUENCE_BONUS",		"+2 [ICON_PRODUCTION] Production towards units in your [ICON_CAPITAL] Capital."	),
	("en_US",	"LOC_CSE_MILITARISTIC_TRAIT_MEDIUM_INFLUENCE_BONUS",	"+2 [ICON_PRODUCTION] Production towards units in every city with a Barracks or Stable."			),
	("en_US",	"LOC_CSE_MILITARISTIC_TRAIT_LARGE_INFLUENCE_BONUS",		"+2 [ICON_PRODUCTION] Production towards units in every city with an Armory."		),
	("en_US",	"LOC_CSE_MILITARISTIC_TRAIT_DESCRIPTION",				"{LOC_MINOR_CIV_SMALL_INFLUENCE_ENVOYS} {LOC_CSE_MILITARISTIC_TRAIT_SMALL_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_MEDIUM_INFLUENCE_ENVOYS} {LOC_CSE_MILITARISTIC_TRAIT_MEDIUM_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_LARGE_INFLUENCE_ENVOYS} {LOC_CSE_MILITARISTIC_TRAIT_LARGE_INFLUENCE_BONUS}"	),

-----------------------------------------------
-- Industrial
-----------------------------------------------
	
	("en_US",	"LOC_CSE_INDUSTRIAL_TRAIT_SMALL_INFLUENCE_BONUS",		"+1 [ICON_PRODUCTION] Production towards districts and buildings in your [ICON_CAPITAL] Capital."	),
	("en_US",	"LOC_CSE_INDUSTRIAL_TRAIT_MEDIUM_INFLUENCE_BONUS",		"+1 [ICON_PRODUCTION] Production towards districts and buildings in every city with a Workshop."		),
	("en_US",	"LOC_CSE_INDUSTRIAL_TRAIT_LARGE_INFLUENCE_BONUS",		"+1 [ICON_PRODUCTION] Production towards districts and buildings in every city with a Factory."		),
	("en_US",	"LOC_CSE_INDUSTRIAL_TRAIT_DESCRIPTION",					"{LOC_MINOR_CIV_SMALL_INFLUENCE_ENVOYS} {LOC_CSE_INDUSTRIAL_TRAIT_SMALL_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_MEDIUM_INFLUENCE_ENVOYS} {LOC_CSE_INDUSTRIAL_TRAIT_MEDIUM_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_LARGE_INFLUENCE_ENVOYS} {LOC_CSE_INDUSTRIAL_TRAIT_LARGE_INFLUENCE_BONUS}"	);
	
