/*
	Icons
	Authors: ChimpanG
*/

-----------------------------------------------
-- IconTextureAtlases
-----------------------------------------------
	
INSERT INTO IconTextureAtlases	
		(Name,									IconSize,	IconsPerRow,	IconsPerColumn,	Filename										)
VALUES  ('ICON_ATLAS_CSE_ALAMUT_ICON',			256,	 	1,				1,				'CSE_ALAMUT_ICON_256.dds'						),
		('ICON_ATLAS_CSE_ALAMUT_ICON',			80,	 		1,				1,				'CSE_ALAMUT_ICON_80.dds'						),
		('ICON_ATLAS_CSE_ALAMUT_ICON',			64,	 		1,				1,				'CSE_ALAMUT_ICON_64.dds'						),
		('ICON_ATLAS_CSE_ALAMUT_ICON',			50,	 		1,				1,				'CSE_ALAMUT_ICON_50.dds'						),
		('ICON_ATLAS_CSE_ALAMUT_ICON',			48,	 		1,				1,				'CSE_ALAMUT_ICON_48.dds'						),
		('ICON_ATLAS_CSE_ALAMUT_ICON',			44,	 		1,				1,				'CSE_ALAMUT_ICON_44.dds'						),
		('ICON_ATLAS_CSE_ALAMUT_ICON',			36,	 		1,				1,				'CSE_ALAMUT_ICON_36.dds'						),
		('ICON_ATLAS_CSE_ALAMUT_ICON',			30,	 		1,				1,				'CSE_ALAMUT_ICON_30.dds'						),
		('ICON_ATLAS_CSE_ALAMUT_ICON',			22,	 		1,				1,				'CSE_ALAMUT_ICON_22.dds'						),

		('ICON_ATLAS_CSE_HASHASHIN_FLAG',		256,		1,				1,				'CIVILIZATION_CSE_HASHASHIN_ICON_256.dds'		),
		('ICON_ATLAS_CSE_HASHASHIN_FLAG',		80,			1,				1,				'CIVILIZATION_CSE_HASHASHIN_ICON_80.dds'		),
		('ICON_ATLAS_CSE_HASHASHIN_FLAG',		32,			1,				1,				'CIVILIZATION_CSE_HASHASHIN_ICON_32.dds'		),
		('ICON_ATLAS_CSE_HASHASHIN_FLAG',		22,			1,				1,				'CIVILIZATION_CSE_HASHASHIN_ICON_22.dds'		),
		
		('ICON_ATLAS_CSE_HASHASHIN_PORTRAIT',	256,		1,				1,				'CIVILIZATION_CSE_HASHASHIN_PORTRAIT_256.dds'	),
		('ICON_ATLAS_CSE_HASHASHIN_PORTRAIT',	200,		1,				1,				'CIVILIZATION_CSE_HASHASHIN_PORTRAIT_200.dds'	),
		('ICON_ATLAS_CSE_HASHASHIN_PORTRAIT',	95,			1,				1,				'CIVILIZATION_CSE_HASHASHIN_PORTRAIT_95.dds'	),
		('ICON_ATLAS_CSE_HASHASHIN_PORTRAIT',	70,			1,				1,				'CIVILIZATION_CSE_HASHASHIN_PORTRAIT_70.dds'	),
		('ICON_ATLAS_CSE_HASHASHIN_PORTRAIT',	50,			1,				1,				'CIVILIZATION_CSE_HASHASHIN_PORTRAIT_50.dds'	),
		('ICON_ATLAS_CSE_HASHASHIN_PORTRAIT',	38,			1,				1,				'CIVILIZATION_CSE_HASHASHIN_PORTRAIT_38.dds'	);

-----------------------------------------------
-- IconDefinitions
-----------------------------------------------

INSERT OR REPLACE INTO IconDefinitions	
		(Name,													Atlas, 									'Index'	)
VALUES	('ICON_CIVILIZATION_CSE_ALAMUT',						'ICON_ATLAS_CSE_ALAMUT_ICON',			0		),
		('ICON_UNIT_CSE_HASHASHIN',								'ICON_ATLAS_CSE_HASHASHIN_FLAG',		0		),
		('ICON_UNIT_CSE_HASHASHIN_BLACK',						'ICON_ATLAS_CSE_HASHASHIN_FLAG',		0		),
		('ICON_UNIT_CSE_HASHASHIN_WHITE',						'ICON_ATLAS_CSE_HASHASHIN_FLAG',		0		),
		('ICON_UNIT_CSE_HASHASHIN_PORTRAIT',					'ICON_ATLAS_CSE_HASHASHIN_PORTRAIT',	0		),
		('ICON_ETHNICITY_AFRICAN_UNIT_CSE_HASHASHIN_PORTRAIT',	'ICON_ATLAS_CSE_HASHASHIN_PORTRAIT',	0		),
		('ICON_ETHNICITY_SOUTHAM_UNIT_CSE_HASHASHIN_PORTRAIT',	'ICON_ATLAS_CSE_HASHASHIN_PORTRAIT',	0		),
		('ICON_ETHNICITY_MEDIT_UNIT_CSE_HASHASHIN_PORTRAIT',	'ICON_ATLAS_CSE_HASHASHIN_PORTRAIT',	0		),
		('ICON_ETHNICITY_ASIAN_UNIT_CSE_HASHASHIN_PORTRAIT',	'ICON_ATLAS_CSE_HASHASHIN_PORTRAIT',	0		);