/*
	Localisation
	Authors: thecrazyscotsman, ChimpanG
*/

INSERT OR REPLACE INTO LocalizedText (Language, Tag, Text)
VALUES

-----------------------------------------------
-- Consular
-----------------------------------------------

	("en_US",	"LOC_CITY_STATES_TYPE_CSE_MARITIME",					"Maritime"	),
	
	("en_US",	"LOC_CSE_MARITIME_TRAIT_SMALL_INFLUENCE_BONUS",			"+1 [ICON_FOOD] Food and +1 [ICON_PRODUCTION] Production in the [ICON_CAPITAL] Capital."	),
	("en_US",	"LOC_CSE_MARITIME_TRAIT_MEDIUM_INFLUENCE_BONUS",		"+1 [ICON_FOOD] Food and +1 [ICON_PRODUCTION] Production in every Lighthouse."		),
	("en_US",	"LOC_CSE_MARITIME_TRAIT_LARGE_INFLUENCE_BONUS",			"+1 [ICON_FOOD] Food and +1 [ICON_PRODUCTION] Production in every Shipyard."	),
	("en_US",	"LOC_CSE_MARITIME_TRAIT_LARGEST_INFLUENCE_BONUS",		"+1 [ICON_FOOD] Food and +1 [ICON_PRODUCTION] Production in every Seaport."	),

	("en_US",	"LOC_CSE_MARITIME_TRAIT_NAME",							"{LOC_CITY_STATES_TYPE_CSE_MARITIME} City-State"	),
	("en_US",	"LOC_CSE_MARITIME_TRAIT_DESCRIPTION",					"{LOC_MINOR_CIV_SMALL_INFLUENCE_ENVOYS} {LOC_CSE_MARITIME_TRAIT_SMALL_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_MEDIUM_INFLUENCE_ENVOYS} {LOC_CSE_MARITIME_TRAIT_MEDIUM_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_LARGE_INFLUENCE_ENVOYS} {LOC_CSE_MARITIME_TRAIT_LARGE_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_LARGEST_INFLUENCE_ENVOYS} {LOC_CSE_MARITIME_TRAIT_LARGEST_INFLUENCE_BONUS}"	),

	("en_US",	"LOC_PEDIA_CITYSTATES_PAGEGROUP_CSE_MARITIME_NAME",		"{LOC_CITY_STATES_TYPE_CSE_MARITIME}"	);
	
